/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsInt, ValidateNested } from "class-validator";
import { MatchCreateNestedManyWithoutUsersInput } from "./MatchCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { SignupCreateNestedManyWithoutUsersInput } from "./SignupCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  draws?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  losses?: number | null;

  @ApiProperty({
    required: false,
    type: () => MatchCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MatchCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MatchCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  matches1?: MatchCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => MatchCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MatchCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MatchCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  matches2?: MatchCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => SignupCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SignupCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SignupCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  signups?: SignupCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tournamentwins?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  wins?: number | null;
}
export { UserCreateInput };
