/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsInt, ValidateNested } from "class-validator";
import { MatchUpdateManyWithoutUsersInput } from "./MatchUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { SignupUpdateManyWithoutUsersInput } from "./SignupUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  draws?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  losses?: number | null;

  @ApiProperty({
    required: false,
    type: () => MatchUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MatchUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MatchUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  matches1?: MatchUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => MatchUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MatchUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MatchUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  matches2?: MatchUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: () => SignupUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SignupUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SignupUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  signups?: SignupUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tournamentwins?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  wins?: number | null;
}
export { UserUpdateInput };
