/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSignupArgs } from "./CreateSignupArgs";
import { UpdateSignupArgs } from "./UpdateSignupArgs";
import { DeleteSignupArgs } from "./DeleteSignupArgs";
import { SignupFindManyArgs } from "./SignupFindManyArgs";
import { SignupFindUniqueArgs } from "./SignupFindUniqueArgs";
import { Signup } from "./Signup";
import { Tournament } from "../../tournament/base/Tournament";
import { User } from "../../user/base/User";
import { SignupService } from "../signup.service";

@graphql.Resolver(() => Signup)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SignupResolverBase {
  constructor(
    protected readonly service: SignupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "read",
    possession: "any",
  })
  async _signupsMeta(
    @graphql.Args() args: SignupFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Signup])
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "read",
    possession: "any",
  })
  async signups(
    @graphql.Args() args: SignupFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Signup[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Signup",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Signup, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "read",
    possession: "own",
  })
  async signup(
    @graphql.Args() args: SignupFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Signup | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Signup",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Signup)
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "create",
    possession: "any",
  })
  async createSignup(
    @graphql.Args() args: CreateSignupArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Signup> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Signup",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Signup"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        tournament: args.data.tournament
          ? {
              connect: args.data.tournament,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Signup)
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "update",
    possession: "any",
  })
  async updateSignup(
    @graphql.Args() args: UpdateSignupArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Signup | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Signup",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Signup"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          tournament: args.data.tournament
            ? {
                connect: args.data.tournament,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Signup)
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "delete",
    possession: "any",
  })
  async deleteSignup(
    @graphql.Args() args: DeleteSignupArgs
  ): Promise<Signup | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Tournament, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "read",
    possession: "any",
  })
  async tournament(
    @graphql.Parent() parent: Signup,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tournament | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tournament",
    });
    const result = await this.service.getTournament(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Signup",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: Signup,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
